BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-//*.bb \
            ${LAYERDIR}/recipes-//*.bbappend"

BBFILE_COLLECTIONS += "agl-quiz"
BBFILE_PATTERN_agl-quiz = "^${LAYERDIR}/"
BBFILE_PRIORITY_agl-quiz = "6"

LAYERDEPENDS_agl-quiz = "core meta-flutter"
LAYERSERIES_COMPAT_agl-quiz = "scarthgap"

LAYER_VERSION_agl-quiz = "1"
LAYER_DESCRIPTION_agl-quiz = "AGL GSoC 2026 Quiz App Yocto Layer"
